from __future__ import annotations

DEFAULT_ENGINE_GRPC_PORT = 50051
DEFAULT_ENGINE_WS_PORT = 50052
DEFAULT_TRITON_GRPC_PORT = 8001
DEFAULT_TRITON_HTTP_PORT = 8000

DEFAULT_ENGINE_WS_PATH = "/v1/ws"
DEFAULT_ENGINE_CAPABILITIES_PATH = "/v1/capabilities"

DEFAULT_TRITON_GRPC_MODEL = "tts_orchestrator"
DEFAULT_TRITON_HTTP_MODEL = "tts_orchestrator_http"
DEFAULT_MODEL_VERSION = "1"

TRANSPORT_ENGINE_WEBSOCKET = "engine-websocket"
TRANSPORT_ENGINE_GRPC = "engine-grpc"
TRANSPORT_TRITON_GRPC = "triton-grpc"
TRANSPORT_TRITON_HTTP = "triton-http"

SUPPORTED_TRANSPORTS = (
    TRANSPORT_ENGINE_WEBSOCKET,
    TRANSPORT_ENGINE_GRPC,
    TRANSPORT_TRITON_GRPC,
    TRANSPORT_TRITON_HTTP,
)
