"""Session-scoped incremental text normalization and commit safety."""

from .types import (
    CommitmentState,
    CommitmentUpdate,
    CommitDecision,
    CommitKind,
    ContentKind,
    FallbackPolicy,
    LanguageEvidence,
    LanguageHypothesis,
    LanguageKind,
    NormalizationCandidate,
    NormalizationResult,
    PrefixResult,
    SemioticSpan,
    SpanKind,
    TextCommit,
    TextInputMetadata,
    TextNormalizationConfig,
)
from .committer import IncrementalTextCommitter
from .causal import (
    CausalFrontier,
    FrontierUpdate,
    FrontierViolation,
    longest_common_unit_prefix,
    spoken_units,
)
from .language import LanguageResolution, LanguageResolver, script_evidence
from .throughput import AudioCreditEstimator, StreamingRateMetrics
from .start_gate import SemanticStartGate
from .wetext_stream import (
    ClosedNormalization,
    StreamSnapshot,
    WetextStream,
    WetextStreamError,
    normalize_closed,
    wetext_runtime_version,
)
from .normalizer_backend import (
    BackendCandidate,
    BackendErrorCode,
    CandidateSource,
    MappedNormalization,
    NormalizationMapping,
    NormalizerBackend,
    NormalizerBackendError,
    PrefixOracleResult,
    PrefixStatus,
    WetextNormalizerBackend,
    WetextPrefixOracle,
)

__all__ = [
    "CommitDecision",
    "CommitmentState",
    "CommitmentUpdate",
    "CommitKind",
    "ContentKind",
    "FallbackPolicy",
    "LanguageEvidence",
    "LanguageHypothesis",
    "LanguageKind",
    "NormalizationCandidate",
    "NormalizationResult",
    "PrefixResult",
    "SemioticSpan",
    "SpanKind",
    "TextCommit",
    "TextInputMetadata",
    "TextNormalizationConfig",
    "IncrementalTextCommitter",
    "CausalFrontier",
    "FrontierUpdate",
    "FrontierViolation",
    "longest_common_unit_prefix",
    "spoken_units",
    "LanguageResolution",
    "LanguageResolver",
    "script_evidence",
    "AudioCreditEstimator",
    "StreamingRateMetrics",
    "SemanticStartGate",
    "ClosedNormalization",
    "StreamSnapshot",
    "WetextStream",
    "WetextStreamError",
    "normalize_closed",
    "wetext_runtime_version",
    "BackendCandidate",
    "BackendErrorCode",
    "CandidateSource",
    "MappedNormalization",
    "NormalizationMapping",
    "NormalizerBackend",
    "NormalizerBackendError",
    "PrefixOracleResult",
    "PrefixStatus",
    "WetextNormalizerBackend",
    "WetextPrefixOracle",
]
