from __future__ import annotations

from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[3]


def _read(path: str) -> str:
    return (REPO_ROOT / path).read_text(encoding="utf-8")


def test_triton_profile_starts_openai_realtime_sidecar_with_internal_grpc():
    compose = yaml.safe_load(_read("infra/docker/compose.yaml"))
    service = compose["services"]["realtime-gateway"]
    triton_build_args = compose["services"]["triton"]["build"]["args"]
    engine_environment = compose["services"]["engine"]["environment"]
    triton_environment = compose["services"]["triton"]["environment"]

    assert service["profiles"] == ["triton"]
    assert service["depends_on"] == ["triton"]
    assert service["environment"]["TRITON_GRPC_ENDPOINT"] == "triton:8001"
    assert service["environment"]["TRITON_REALTIME_PORT"] == 50052
    assert service["ports"] == ["${TRITON_REALTIME_HOST_PORT:-50053}:50052"]
    assert "gpus" not in service
    assert any("workspace/realtime_usage" in volume for volume in service["volumes"])
    assert triton_build_args["CLIENT_WHEEL_FILENAME"] == "${CLIENT_WHEEL_FILENAME:-}"
    assert triton_build_args["CLIENT_WHEEL_SHA256"] == "${CLIENT_WHEEL_SHA256:-}"
    assert triton_build_args["TRITON_RUNTIME_BASE_IMAGE"] == (
        "${TRITON_RUNTIME_BASE_IMAGE:-triton-deps}"
    )
    assert "QWEN3_TTS_ENGINE_BUILD_VERSION" not in engine_environment
    assert "QWEN3_TTS_ENGINE_BUILD_VERSION" not in triton_environment
    assert service["command"][-3:] == [
        "python3",
        "-m",
        "engine.gateway.triton_realtime_server",
    ]


def test_triton_image_contains_sidecar_runtime_dependencies_and_protocol():
    dockerfile = _read("infra/docker/Dockerfile.triton")

    dependency_runs = dockerfile.split("RUN --mount=type=cache,target=/root/.cache/pip")
    assert len(dependency_runs) == 3
    assert "    attrs \\\n" not in dependency_runs[1]
    assert "    attrs \\\n" in dependency_runs[2]
    assert "    packaging \\\n" in dependency_runs[2]
    assert "    'pypinyin>=0.55,<1' \\\n" in dependency_runs[2]
    assert "    'wetext==0.1.7' \\\n" in dependency_runs[2]
    assert "pip install --force-reinstall --no-deps" in dependency_runs[2]
    assert "    attrs \\\n" in dockerfile
    assert "aiohttp" in dockerfile
    assert "import aiohttp, attr" in dockerfile
    assert "'wetext==0.1.7'" in dockerfile
    assert "import aiohttp, attr, packaging, wetext" in dockerfile
    assert "ARG TRITON_RUNTIME_BASE_IMAGE=triton-deps" in dockerfile
    assert "ARG TRITON_RUNTIME_PARENT_IMAGE=triton-heavy-deps" in dockerfile
    assert "FROM ${BASE_IMAGE} AS triton-heavy-deps" in dockerfile
    assert "FROM ${TRITON_RUNTIME_PARENT_IMAGE} AS triton-deps" in dockerfile
    assert "FROM ${TRITON_RUNTIME_BASE_IMAGE} AS triton-runtime" in dockerfile
    assert 'ARG TRITON_RUNTIME_BASE_REFERENCE=""' in dockerfile
    assert "io.qwen3tts.triton-runtime-base.reference" in dockerfile
    assert "PYTHONPATH=/opt/qwen3-tts:${PYTHONPATH}" in dockerfile
    assert '"tritonclient[grpc]>=2.54.0"' in dockerfile
    assert (
        "COPY client/src/qwen3tts_protocol/ /opt/qwen3-tts/qwen3tts_protocol/"
        in dockerfile
    )
    assert 'ARG CLIENT_WHEEL_FILENAME=""' in dockerfile
    assert 'ARG CLIENT_WHEEL_SHA256=""' in dockerfile
    assert "COPY client/dist/ /app/sdk/" in dockerfile
    assert "find /app/sdk -maxdepth 1" in dockerfile
    assert "sha256sum -c -" in dockerfile


def test_compose_wrapper_manages_sidecar_with_triton_lifecycle():
    script = _read("scripts/bash/compose.sh")
    deploy = _read("scripts/bash/deploy.sh")
    autorun = _read("scripts/bash/autorun.sh")

    assert "_compose_up_exec triton realtime-gateway" in script
    assert "compose_wait_triton_realtime_ready" in script
    assert "args+=(triton realtime-gateway)" in script
    assert "compose_cmd stop realtime-gateway triton" in script
    assert '--realtime-port) TRITON_REALTIME="$2"' in script
    assert '--realtime-port)  COMPOSE_EXTRA+=(--realtime-port "$2")' in deploy
    assert '--realtime-port)    REALTIME_PORT="$2"' in autorun
    assert "append_optarg DEPLOY_ARGS --realtime-port" in autorun
    assert "模型发布版本 MODEL_VERSION" in autorun
    assert "ENGINE_BUILD_VERSION is generated by Phase B" in autorun
    assert "打包日期 YYYY-MM-DD" in autorun


def test_release_pipelines_build_both_version_matched_runtime_images():
    github = _read(".github/workflows/release.yml")
    gitlab = _read(".gitlab-ci.yml")

    for pipeline in (github, gitlab):
        assert "--file infra/docker/Dockerfile.engine" in pipeline
        assert "--file infra/docker/Dockerfile.triton" in pipeline
        assert "BROWSER_SDK_VERSION" in pipeline
        assert "CLIENT_WHEEL_SHA256" in pipeline
        assert "/app/demo/index.html" in pipeline
        assert "engine.distribution.container_smoke --runtime standalone" in pipeline
        assert "engine.distribution.container_smoke --runtime triton" in pipeline
        assert 'TRITON_RUNTIME_BASE_IMAGE=' in pipeline
        assert '--build-arg "TRITON_RUNTIME_BASE_IMAGE=' in pipeline

    assert "triton_image" in github
    assert "TRITON_RELEASE_IMAGE" in gitlab


def test_release_uses_an_immutable_prebuilt_triton_dependency_base():
    github_release = _read(".github/workflows/release.yml")
    github_base = _read(".github/workflows/triton-runtime-base.yml")
    gitlab = _read(".gitlab-ci.yml")
    publisher = _read("scripts/bash/publish_triton_runtime_base.sh")

    assert 'BUILD_TRITON_RUNTIME_BASE == "1"' in gitlab
    assert "build-triton-runtime-base:" in gitlab
    base_job = gitlab.split("\nbuild-triton-runtime-base:\n", 1)[1].split(
        "\nbuild-web-release:\n", 1
    )[0]
    assert "apk add --no-cache bash" in base_job
    assert "Required Triton runtime base is missing" in gitlab
    assert "Required Triton runtime base is missing" in github_release
    assert "workflow_dispatch:" in github_base
    assert "scripts/bash/publish_triton_runtime_base.sh" in gitlab
    assert "scripts/bash/publish_triton_runtime_base.sh" in github_base
    assert "--target triton-deps" in publisher
    assert 'docker push "$runtime_base_image"' in publisher
    assert "docker manifest inspect" in publisher
    assert 'docker pull "$runtime_parent_image"' in publisher
    assert 'TRITON_RUNTIME_PARENT_IMAGE=$runtime_parent_image' in publisher
    assert "TRITON_RUNTIME_PARENT_TAG" in gitlab
    assert "TRITON_RUNTIME_PARENT_TAG" in github_base
    for release in (github_release, gitlab):
        assert "TRITON_RUNTIME_BASE_DIGEST" in release.upper()
        assert "--no-cache" in release
        assert "io.qwen3tts.triton-runtime-base.reference" in release
        assert "--env PYTHONPATH=/opt/qwen3-tts" not in release
        triton_build = release.split("--file infra/docker/Dockerfile.triton", 1)[1]
        assert '--cache-from "$TRITON_BUILD_CACHE_IMAGE"' not in triton_build
        assert '--cache-from "$triton_cache_image"' not in triton_build


def test_gitlab_web_release_uses_the_matching_preinstalled_playwright_image():
    gitlab = _read(".gitlab-ci.yml")
    package_lock = _read("web/package-lock.json")
    web_job = gitlab.split("\nbuild-web-release:\n", 1)[1].split(
        "\nbuild-client-wheel:\n", 1
    )[0]

    assert '"@playwright/test": "1.55.0"' in package_lock
    assert (
        'RUNNER_PLAYWRIGHT_IMAGE: "mcr.microsoft.com/playwright:v1.55.0-noble"'
        in gitlab
    )
    assert 'image: "$RUNNER_PLAYWRIGHT_IMAGE"' in web_job
    assert "playwright install" not in web_job


def test_web_release_stamps_only_the_publishable_workspace_without_registry_resolution():
    script = _read("scripts/bash/release_web.sh")

    assert "--workspace @xmultimodalinteraction/qwen3tts-browser" in script
    assert "--workspaces-update=false" in script
    assert "--workspace @xmultimodalinteraction/qwen3tts-demo" not in script
    assert script.index("npm run build") < script.index('npm version "$semver"')
    assert script.index('npm version "$semver"') < script.index("npm run pack:browser")


def test_local_compose_uses_reproducible_node_builder_for_web_artifacts():
    compose_script = _read("scripts/bash/compose.sh")
    dockerfile = _read("infra/docker/Dockerfile.web-builder")

    assert "Dockerfile.web-builder" in compose_script
    # Keep Phase C independent from Docker Hub's Dockerfile frontend registry.
    # The local BuildKit frontend supports the cache mount used below.
    assert "docker/dockerfile:" not in dockerfile
    assert "--target web-artifacts" in compose_script
    assert '--output "type=local,dest=$staged_web"' in compose_script
    assert "FROM ${NODE_IMAGE} AS web-builder" in dockerfile
    assert "npm --prefix web ci" in dockerfile
    assert "npm --prefix web run build" in dockerfile
    assert "npm --prefix web run pack:browser" in dockerfile
    assert "/out/demo/downloads" in dockerfile
    assert "browser-sdk-tarball.txt" in dockerfile
    assert "FROM scratch AS web-artifacts" in dockerfile


def test_runtime_images_fail_closed_when_demo_artifact_is_missing():
    for path in (
        "infra/docker/Dockerfile.engine",
        "infra/docker/Dockerfile.triton",
    ):
        dockerfile = _read(path)
        assert "COPY web/packages/demo/dist/ /app/demo/" in dockerfile
        assert "test -s /app/demo/index.html" in dockerfile
        assert "xmultimodalinteraction-qwen3tts-browser-*.tgz" in dockerfile
        assert "Demo artifact missing" in dockerfile


def test_tn_runtime_dependency_is_baked_into_standalone_and_generated_images():
    engine = _read("infra/docker/Dockerfile.engine")
    generated = _read("scripts/bash/build_triton.sh")
    setup = _read("scripts/bash/setup_env.sh")
    assert "'wetext==0.1.7'" in engine
    assert "import torch, tokenizers, yaml, grpc, numpy, soxr, wetext" in engine
    assert "wetext==0.1.7" in generated
    assert "import wetext, pypinyin" in generated
    assert "wetext==0.1.7" in setup
    for path in (
        "infra/docker/Dockerfile.engine",
        "infra/docker/Dockerfile.triton",
        "infra/docker/Dockerfile.triton.local-validation",
        "Dockerfile.triton",
        "scripts/bash/build_triton.sh",
        "scripts/bash/lib/triton.sh",
        "scripts/bash/setup_env.sh",
    ):
        assert "'pypinyin>=0.55,<1'" in _read(path), path
