"""Canonical external session/interface contract helpers."""

from .output import OutputPipeline, build_done_event, build_forward_event, build_start_event
from .protocol import (
    PROTOCOL_VERSION,
    SUPPORTED_OUTPUT_POLICY_FEATURES,
    SUPPORTED_TIMING_FIELDS,
    SUPPORTED_VAD_STRATEGIES,
    normalize_capabilities,
    parse_output_policy,
    parse_timing_context,
    serialize_output_policy,
    serialize_stream_event,
    serialize_timing_context,
    to_core_output_policy,
    to_core_timing_context,
)
from .types import (
    AudioFrame,
    OutputPolicy,
    SessionEndRequest,
    SessionStartRequest,
    StreamCancelRequest,
    StreamEvent,
    StreamTextChunk,
    TimingContext,
    VADPolicy,
)
from .vad import (
    TTSVADConfig,
    TTSVADProcessor,
    VADMode,
    create_vad_processor,
    vad_config_from_dict,
    EnergyVADProcessor,
    TenVADProcessor,
    DisabledVADProcessor,
)

__all__ = (
    "AudioFrame",
    "DisabledVADProcessor",
    "EnergyVADProcessor",
    "OutputPipeline",
    "OutputPolicy",
    "PROTOCOL_VERSION",
    "SUPPORTED_OUTPUT_POLICY_FEATURES",
    "SUPPORTED_TIMING_FIELDS",
    "SUPPORTED_VAD_STRATEGIES",
    "SessionEndRequest",
    "SessionStartRequest",
    "StreamCancelRequest",
    "StreamEvent",
    "StreamTextChunk",
    "TENVADProcessor",
    "TTSVADConfig",
    "TTSVADProcessor",
    "TimingContext",
    "VADMode",
    "VADPolicy",
    "build_done_event",
    "build_forward_event",
    "build_start_event",
    "create_vad_processor",
    "normalize_capabilities",
    "parse_output_policy",
    "parse_timing_context",
    "serialize_output_policy",
    "serialize_stream_event",
    "serialize_timing_context",
    "to_core_output_policy",
    "to_core_timing_context",
    "vad_config_from_dict",
)
