from __future__ import annotations

DEFAULT_ENGINE_GRPC_PORT = 50051
DEFAULT_ENGINE_WS_PORT = 50052
DEFAULT_TRITON_REALTIME_PORT = 50053
DEFAULT_TRITON_GRPC_PORT = 8001
DEFAULT_TRITON_HTTP_PORT = 8000

DEFAULT_ENGINE_WS_PATH = "/v1/ws"
DEFAULT_OPENAI_REALTIME_PATH = "/v1/realtime"
DEFAULT_ENGINE_CAPABILITIES_PATH = "/v1/capabilities"

DEFAULT_TRITON_GRPC_MODEL = "tts_orchestrator"
DEFAULT_TRITON_HTTP_MODEL = "tts_orchestrator_http"
DEFAULT_OPENAI_REALTIME_MODEL = "qwen3-tts-realtime"
DEFAULT_MODEL_VERSION = "1"

OPENAI_REALTIME_PROTOCOL = "openai-realtime-v1"
QWEN_REALTIME_EXTENSION_PROTOCOL = "qwen-realtime-v1"
QWEN_TEXT_BUFFER_EXTENSION = "qwen.input_text_buffer.v1"
QWEN_TEXT_PROGRESS_EXTENSION = "qwen.text_progress.v1"
QWEN_RESPONSE_RESUME_EXTENSION = "qwen.response_resume.v1"

TRANSPORT_OPENAI_REALTIME = "openai-realtime"
TRANSPORT_ENGINE_WEBSOCKET = "engine-websocket"
TRANSPORT_ENGINE_GRPC = "engine-grpc"
TRANSPORT_TRITON_GRPC = "triton-grpc"
TRANSPORT_TRITON_HTTP = "triton-http"

SUPPORTED_TRANSPORTS = (
    TRANSPORT_OPENAI_REALTIME,
    TRANSPORT_ENGINE_WEBSOCKET,
    TRANSPORT_ENGINE_GRPC,
    TRANSPORT_TRITON_GRPC,
    TRANSPORT_TRITON_HTTP,
)
